builders:
  nimbus_supporter:
    import: "package:nimbus_generator/builder.dart"
    builder_factories: ["nimbusSupporter"]
    build_extensions: {".dart": [".nimbus_annotation.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]